version: 2.1

_run:
  prepare: &prepare
    name: "Preparing environment"
    command: |
      make prepare

jobs:
  checkout-code:
    machine:
      enabled: true
    steps:
      - checkout
      - persist_to_workspace:
            root: ~/project
            paths:
              - ./

  lint-php:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Linting changed PHP files on PR
          command: |
            make lint

workflows:
  version: 2
  build:
    jobs:
      - checkout-code
      - lint-php:
          requires:
          - checkout-code